apiVersion: 1

deleteDatasources:
  - name: Prometheus

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: DefinePrometheusURL
  isDefault: true
  version: 1
  editable: true


